apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.8.0.2:6443
    token: "tbwkyi.2mfov6fuswn2e8nj"
    caCertHashes:
    - "sha256:fcbfcdbf02772ce13d0b073454c0514e71f146c3f9f13a11ac15cd3fb698d778"
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "10.8.1.2,fc00:0:0800:1::2"