apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.8.0.2:6443
    token: "gmf3ca.yn8k3lt565jxiajg"
    caCertHashes:
    - "sha256:d83ab312a92892bae53392b86e346c52b691ecf7c802e18613cb56af9df3a5c2"
nodeRegistration:
  kubeletExtraArgs:
  - name: "node-ip"
    value: "10.8.1.2,fc00:0:0800:1::2"