# ansible-playbook -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -i hosts vms_k8s_workers.yaml -vv

- name: join vm-01 to cluster
  hosts: 192.168.122.101
  become: true
  tasks:

    - name: copy k8s-join.yaml for vm-01
      copy:
        src: /home/cisco/LTRSPG-2212/infrastructure/vms/vm-01/vm-01-k8s-join.yaml
        dest: /tmp/k8s-join.yaml
      ignore_errors: yes

    - name: kubeadm join
      command: kubeadm join --config /tmp/k8s-join.yaml --v=5
      ignore_errors: yes

- name: join vm-02 to cluster
  hosts: 192.168.122.102
  become: true
  tasks:

    - name: copy k8s-join.yaml for vm-02
      copy:
        src: /home/cisco/LTRSPG-2212/infrastructure/vms/vm-02/vm-02-k8s-join.yaml
        dest: /tmp/k8s-join.yaml
      ignore_errors: yes

    - name: kubeadm join
      command: kubeadm join --config /tmp/k8s-join.yaml
      ignore_errors: yes

- name: k8s control plane
  hosts: k8s_cp
  tasks:

    - name: get nodes -o wide
      command: kubectl get nodes -o wide
      register: nodes
      ignore_errors: yes

    - name: show nodes -o wide
      debug:
        msg: "{{ nodes.stdout_lines }}"

    - name: get pods status
      command: kubectl get pods --all-namespaces
      register: pods
      ignore_errors: yes

    - name: show pods status
      debug:
        msg: "{{ pods.stdout_lines }}"

    - name: untaint control plane
      command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
      ignore_errors: yes
